/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppVentesRouteImport } from './routes/_app.ventes'
import { Route as AppUtilisateursRouteImport } from './routes/_app.utilisateurs'
import { Route as AppTresorerieRouteImport } from './routes/_app.tresorerie'
import { Route as AppStocksRouteImport } from './routes/_app.stocks'
import { Route as AppRelancesRouteImport } from './routes/_app.relances'
import { Route as AppRapportsRouteImport } from './routes/_app.rapports'
import { Route as AppPartenairesRouteImport } from './routes/_app.partenaires'
import { Route as AppParametresRouteImport } from './routes/_app.parametres'
import { Route as AppMaintenanceRouteImport } from './routes/_app.maintenance'
import { Route as AppLotissementsRouteImport } from './routes/_app.lotissements'
import { Route as AppEcheanciersRouteImport } from './routes/_app.echeanciers'
import { Route as AppComptabiliteRouteImport } from './routes/_app.comptabilite'
import { Route as AppCommissionsRouteImport } from './routes/_app.commissions'
import { Route as AppChantiersRouteImport } from './routes/_app.chantiers'
import { Route as AppProprietairesIndexRouteImport } from './routes/_app.proprietaires.index'
import { Route as AppLoyersIndexRouteImport } from './routes/_app.loyers.index'
import { Route as AppLocatairesIndexRouteImport } from './routes/_app.locataires.index'
import { Route as AppContratsIndexRouteImport } from './routes/_app.contrats.index'
import { Route as AppBiensIndexRouteImport } from './routes/_app.biens.index'
import { Route as AppLocatairesNouveauRouteImport } from './routes/_app.locataires.nouveau'
import { Route as AppLocatairesIdRouteImport } from './routes/_app.locataires.$id'
import { Route as AppContratsNouveauRouteImport } from './routes/_app.contrats.nouveau'
import { Route as AppContratsIdRouteImport } from './routes/_app.contrats.$id'
import { Route as AppBiensNouveauRouteImport } from './routes/_app.biens.nouveau'
import { Route as AppBiensIdRouteImport } from './routes/_app.biens.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVentesRoute = AppVentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => AppRoute,
} as any)
const AppUtilisateursRoute = AppUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AppRoute,
} as any)
const AppTresorerieRoute = AppTresorerieRouteImport.update({
  id: '/tresorerie',
  path: '/tresorerie',
  getParentRoute: () => AppRoute,
} as any)
const AppStocksRoute = AppStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AppRoute,
} as any)
const AppRelancesRoute = AppRelancesRouteImport.update({
  id: '/relances',
  path: '/relances',
  getParentRoute: () => AppRoute,
} as any)
const AppRapportsRoute = AppRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AppRoute,
} as any)
const AppPartenairesRoute = AppPartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppLotissementsRoute = AppLotissementsRouteImport.update({
  id: '/lotissements',
  path: '/lotissements',
  getParentRoute: () => AppRoute,
} as any)
const AppEcheanciersRoute = AppEcheanciersRouteImport.update({
  id: '/echeanciers',
  path: '/echeanciers',
  getParentRoute: () => AppRoute,
} as any)
const AppComptabiliteRoute = AppComptabiliteRouteImport.update({
  id: '/comptabilite',
  path: '/comptabilite',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppChantiersRoute = AppChantiersRouteImport.update({
  id: '/chantiers',
  path: '/chantiers',
  getParentRoute: () => AppRoute,
} as any)
const AppProprietairesIndexRoute = AppProprietairesIndexRouteImport.update({
  id: '/proprietaires/',
  path: '/proprietaires/',
  getParentRoute: () => AppRoute,
} as any)
const AppLoyersIndexRoute = AppLoyersIndexRouteImport.update({
  id: '/loyers/',
  path: '/loyers/',
  getParentRoute: () => AppRoute,
} as any)
const AppLocatairesIndexRoute = AppLocatairesIndexRouteImport.update({
  id: '/locataires/',
  path: '/locataires/',
  getParentRoute: () => AppRoute,
} as any)
const AppContratsIndexRoute = AppContratsIndexRouteImport.update({
  id: '/contrats/',
  path: '/contrats/',
  getParentRoute: () => AppRoute,
} as any)
const AppBiensIndexRoute = AppBiensIndexRouteImport.update({
  id: '/biens/',
  path: '/biens/',
  getParentRoute: () => AppRoute,
} as any)
const AppLocatairesNouveauRoute = AppLocatairesNouveauRouteImport.update({
  id: '/locataires/nouveau',
  path: '/locataires/nouveau',
  getParentRoute: () => AppRoute,
} as any)
const AppLocatairesIdRoute = AppLocatairesIdRouteImport.update({
  id: '/locataires/$id',
  path: '/locataires/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContratsNouveauRoute = AppContratsNouveauRouteImport.update({
  id: '/contrats/nouveau',
  path: '/contrats/nouveau',
  getParentRoute: () => AppRoute,
} as any)
const AppContratsIdRoute = AppContratsIdRouteImport.update({
  id: '/contrats/$id',
  path: '/contrats/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBiensNouveauRoute = AppBiensNouveauRouteImport.update({
  id: '/biens/nouveau',
  path: '/biens/nouveau',
  getParentRoute: () => AppRoute,
} as any)
const AppBiensIdRoute = AppBiensIdRouteImport.update({
  id: '/biens/$id',
  path: '/biens/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/chantiers': typeof AppChantiersRoute
  '/commissions': typeof AppCommissionsRoute
  '/comptabilite': typeof AppComptabiliteRoute
  '/echeanciers': typeof AppEcheanciersRoute
  '/lotissements': typeof AppLotissementsRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/parametres': typeof AppParametresRoute
  '/partenaires': typeof AppPartenairesRoute
  '/rapports': typeof AppRapportsRoute
  '/relances': typeof AppRelancesRoute
  '/stocks': typeof AppStocksRoute
  '/tresorerie': typeof AppTresorerieRoute
  '/utilisateurs': typeof AppUtilisateursRoute
  '/ventes': typeof AppVentesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/biens/$id': typeof AppBiensIdRoute
  '/biens/nouveau': typeof AppBiensNouveauRoute
  '/contrats/$id': typeof AppContratsIdRoute
  '/contrats/nouveau': typeof AppContratsNouveauRoute
  '/locataires/$id': typeof AppLocatairesIdRoute
  '/locataires/nouveau': typeof AppLocatairesNouveauRoute
  '/biens/': typeof AppBiensIndexRoute
  '/contrats/': typeof AppContratsIndexRoute
  '/locataires/': typeof AppLocatairesIndexRoute
  '/loyers/': typeof AppLoyersIndexRoute
  '/proprietaires/': typeof AppProprietairesIndexRoute
}
export interface FileRoutesByTo {
  '/chantiers': typeof AppChantiersRoute
  '/commissions': typeof AppCommissionsRoute
  '/comptabilite': typeof AppComptabiliteRoute
  '/echeanciers': typeof AppEcheanciersRoute
  '/lotissements': typeof AppLotissementsRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/parametres': typeof AppParametresRoute
  '/partenaires': typeof AppPartenairesRoute
  '/rapports': typeof AppRapportsRoute
  '/relances': typeof AppRelancesRoute
  '/stocks': typeof AppStocksRoute
  '/tresorerie': typeof AppTresorerieRoute
  '/utilisateurs': typeof AppUtilisateursRoute
  '/ventes': typeof AppVentesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof AppIndexRoute
  '/biens/$id': typeof AppBiensIdRoute
  '/biens/nouveau': typeof AppBiensNouveauRoute
  '/contrats/$id': typeof AppContratsIdRoute
  '/contrats/nouveau': typeof AppContratsNouveauRoute
  '/locataires/$id': typeof AppLocatairesIdRoute
  '/locataires/nouveau': typeof AppLocatairesNouveauRoute
  '/biens': typeof AppBiensIndexRoute
  '/contrats': typeof AppContratsIndexRoute
  '/locataires': typeof AppLocatairesIndexRoute
  '/loyers': typeof AppLoyersIndexRoute
  '/proprietaires': typeof AppProprietairesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/chantiers': typeof AppChantiersRoute
  '/_app/commissions': typeof AppCommissionsRoute
  '/_app/comptabilite': typeof AppComptabiliteRoute
  '/_app/echeanciers': typeof AppEcheanciersRoute
  '/_app/lotissements': typeof AppLotissementsRoute
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/parametres': typeof AppParametresRoute
  '/_app/partenaires': typeof AppPartenairesRoute
  '/_app/rapports': typeof AppRapportsRoute
  '/_app/relances': typeof AppRelancesRoute
  '/_app/stocks': typeof AppStocksRoute
  '/_app/tresorerie': typeof AppTresorerieRoute
  '/_app/utilisateurs': typeof AppUtilisateursRoute
  '/_app/ventes': typeof AppVentesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/': typeof AppIndexRoute
  '/_app/biens/$id': typeof AppBiensIdRoute
  '/_app/biens/nouveau': typeof AppBiensNouveauRoute
  '/_app/contrats/$id': typeof AppContratsIdRoute
  '/_app/contrats/nouveau': typeof AppContratsNouveauRoute
  '/_app/locataires/$id': typeof AppLocatairesIdRoute
  '/_app/locataires/nouveau': typeof AppLocatairesNouveauRoute
  '/_app/biens/': typeof AppBiensIndexRoute
  '/_app/contrats/': typeof AppContratsIndexRoute
  '/_app/locataires/': typeof AppLocatairesIndexRoute
  '/_app/loyers/': typeof AppLoyersIndexRoute
  '/_app/proprietaires/': typeof AppProprietairesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chantiers'
    | '/commissions'
    | '/comptabilite'
    | '/echeanciers'
    | '/lotissements'
    | '/maintenance'
    | '/parametres'
    | '/partenaires'
    | '/rapports'
    | '/relances'
    | '/stocks'
    | '/tresorerie'
    | '/utilisateurs'
    | '/ventes'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/biens/$id'
    | '/biens/nouveau'
    | '/contrats/$id'
    | '/contrats/nouveau'
    | '/locataires/$id'
    | '/locataires/nouveau'
    | '/biens/'
    | '/contrats/'
    | '/locataires/'
    | '/loyers/'
    | '/proprietaires/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chantiers'
    | '/commissions'
    | '/comptabilite'
    | '/echeanciers'
    | '/lotissements'
    | '/maintenance'
    | '/parametres'
    | '/partenaires'
    | '/rapports'
    | '/relances'
    | '/stocks'
    | '/tresorerie'
    | '/utilisateurs'
    | '/ventes'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/'
    | '/biens/$id'
    | '/biens/nouveau'
    | '/contrats/$id'
    | '/contrats/nouveau'
    | '/locataires/$id'
    | '/locataires/nouveau'
    | '/biens'
    | '/contrats'
    | '/locataires'
    | '/loyers'
    | '/proprietaires'
  id:
    | '__root__'
    | '/_app'
    | '/_app/chantiers'
    | '/_app/commissions'
    | '/_app/comptabilite'
    | '/_app/echeanciers'
    | '/_app/lotissements'
    | '/_app/maintenance'
    | '/_app/parametres'
    | '/_app/partenaires'
    | '/_app/rapports'
    | '/_app/relances'
    | '/_app/stocks'
    | '/_app/tresorerie'
    | '/_app/utilisateurs'
    | '/_app/ventes'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/_app/'
    | '/_app/biens/$id'
    | '/_app/biens/nouveau'
    | '/_app/contrats/$id'
    | '/_app/contrats/nouveau'
    | '/_app/locataires/$id'
    | '/_app/locataires/nouveau'
    | '/_app/biens/'
    | '/_app/contrats/'
    | '/_app/locataires/'
    | '/_app/loyers/'
    | '/_app/proprietaires/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ventes': {
      id: '/_app/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof AppVentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/utilisateurs': {
      id: '/_app/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AppUtilisateursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tresorerie': {
      id: '/_app/tresorerie'
      path: '/tresorerie'
      fullPath: '/tresorerie'
      preLoaderRoute: typeof AppTresorerieRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stocks': {
      id: '/_app/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AppStocksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relances': {
      id: '/_app/relances'
      path: '/relances'
      fullPath: '/relances'
      preLoaderRoute: typeof AppRelancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rapports': {
      id: '/_app/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AppRapportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partenaires': {
      id: '/_app/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof AppPartenairesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres': {
      id: '/_app/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lotissements': {
      id: '/_app/lotissements'
      path: '/lotissements'
      fullPath: '/lotissements'
      preLoaderRoute: typeof AppLotissementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/echeanciers': {
      id: '/_app/echeanciers'
      path: '/echeanciers'
      fullPath: '/echeanciers'
      preLoaderRoute: typeof AppEcheanciersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comptabilite': {
      id: '/_app/comptabilite'
      path: '/comptabilite'
      fullPath: '/comptabilite'
      preLoaderRoute: typeof AppComptabiliteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commissions': {
      id: '/_app/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chantiers': {
      id: '/_app/chantiers'
      path: '/chantiers'
      fullPath: '/chantiers'
      preLoaderRoute: typeof AppChantiersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proprietaires/': {
      id: '/_app/proprietaires/'
      path: '/proprietaires'
      fullPath: '/proprietaires/'
      preLoaderRoute: typeof AppProprietairesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loyers/': {
      id: '/_app/loyers/'
      path: '/loyers'
      fullPath: '/loyers/'
      preLoaderRoute: typeof AppLoyersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locataires/': {
      id: '/_app/locataires/'
      path: '/locataires'
      fullPath: '/locataires/'
      preLoaderRoute: typeof AppLocatairesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contrats/': {
      id: '/_app/contrats/'
      path: '/contrats'
      fullPath: '/contrats/'
      preLoaderRoute: typeof AppContratsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biens/': {
      id: '/_app/biens/'
      path: '/biens'
      fullPath: '/biens/'
      preLoaderRoute: typeof AppBiensIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locataires/nouveau': {
      id: '/_app/locataires/nouveau'
      path: '/locataires/nouveau'
      fullPath: '/locataires/nouveau'
      preLoaderRoute: typeof AppLocatairesNouveauRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locataires/$id': {
      id: '/_app/locataires/$id'
      path: '/locataires/$id'
      fullPath: '/locataires/$id'
      preLoaderRoute: typeof AppLocatairesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contrats/nouveau': {
      id: '/_app/contrats/nouveau'
      path: '/contrats/nouveau'
      fullPath: '/contrats/nouveau'
      preLoaderRoute: typeof AppContratsNouveauRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contrats/$id': {
      id: '/_app/contrats/$id'
      path: '/contrats/$id'
      fullPath: '/contrats/$id'
      preLoaderRoute: typeof AppContratsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biens/nouveau': {
      id: '/_app/biens/nouveau'
      path: '/biens/nouveau'
      fullPath: '/biens/nouveau'
      preLoaderRoute: typeof AppBiensNouveauRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biens/$id': {
      id: '/_app/biens/$id'
      path: '/biens/$id'
      fullPath: '/biens/$id'
      preLoaderRoute: typeof AppBiensIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChantiersRoute: typeof AppChantiersRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppComptabiliteRoute: typeof AppComptabiliteRoute
  AppEcheanciersRoute: typeof AppEcheanciersRoute
  AppLotissementsRoute: typeof AppLotissementsRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppParametresRoute: typeof AppParametresRoute
  AppPartenairesRoute: typeof AppPartenairesRoute
  AppRapportsRoute: typeof AppRapportsRoute
  AppRelancesRoute: typeof AppRelancesRoute
  AppStocksRoute: typeof AppStocksRoute
  AppTresorerieRoute: typeof AppTresorerieRoute
  AppUtilisateursRoute: typeof AppUtilisateursRoute
  AppVentesRoute: typeof AppVentesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBiensIdRoute: typeof AppBiensIdRoute
  AppBiensNouveauRoute: typeof AppBiensNouveauRoute
  AppContratsIdRoute: typeof AppContratsIdRoute
  AppContratsNouveauRoute: typeof AppContratsNouveauRoute
  AppLocatairesIdRoute: typeof AppLocatairesIdRoute
  AppLocatairesNouveauRoute: typeof AppLocatairesNouveauRoute
  AppBiensIndexRoute: typeof AppBiensIndexRoute
  AppContratsIndexRoute: typeof AppContratsIndexRoute
  AppLocatairesIndexRoute: typeof AppLocatairesIndexRoute
  AppLoyersIndexRoute: typeof AppLoyersIndexRoute
  AppProprietairesIndexRoute: typeof AppProprietairesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChantiersRoute: AppChantiersRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppComptabiliteRoute: AppComptabiliteRoute,
  AppEcheanciersRoute: AppEcheanciersRoute,
  AppLotissementsRoute: AppLotissementsRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppParametresRoute: AppParametresRoute,
  AppPartenairesRoute: AppPartenairesRoute,
  AppRapportsRoute: AppRapportsRoute,
  AppRelancesRoute: AppRelancesRoute,
  AppStocksRoute: AppStocksRoute,
  AppTresorerieRoute: AppTresorerieRoute,
  AppUtilisateursRoute: AppUtilisateursRoute,
  AppVentesRoute: AppVentesRoute,
  AppIndexRoute: AppIndexRoute,
  AppBiensIdRoute: AppBiensIdRoute,
  AppBiensNouveauRoute: AppBiensNouveauRoute,
  AppContratsIdRoute: AppContratsIdRoute,
  AppContratsNouveauRoute: AppContratsNouveauRoute,
  AppLocatairesIdRoute: AppLocatairesIdRoute,
  AppLocatairesNouveauRoute: AppLocatairesNouveauRoute,
  AppBiensIndexRoute: AppBiensIndexRoute,
  AppContratsIndexRoute: AppContratsIndexRoute,
  AppLocatairesIndexRoute: AppLocatairesIndexRoute,
  AppLoyersIndexRoute: AppLoyersIndexRoute,
  AppProprietairesIndexRoute: AppProprietairesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
